- name: Create vhost directory
  ansible.builtin.file:
    path: /var/www/{{  domain_name  }}/html
    state: directory
- name: Upload virtual host index file
  template:
    src: index.html.j2
    dest: /var/www/{{  domain_name  }}/html/index.html
- name: Upload virtual host config file
  template:
    src: vhost.conf.j2
    dest: /etc/nginx/conf.d/{{  domain_name  }}.conf
  notify: Reload Nginx
