version: "3.7"
services:
  redis:
    image: redis:4-alpine
    ports:
      - 16379:6379
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: voting
      MYSQL_DATABASE: voting
      MYSQL_USER: voting
      MYSQL_PASSWORD: voting
    ports:
      - 3306:3306
  voting:
    image: voting
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_PASSWORD: voting
      DB_USERNAME: voting
      DB_DATABASE: voting
    depends_on:
      - mysql
      - redis
    ports:
      - "9000:80"
  nginx:
    image: nginx:alpine
    depends_on:
      - voting
    volumes:
     - type: bind
       source: ./nginx/default.conf
       target: /etc/nginx/conf.d/default.conf
    deploy:
      mode: replicated
      replicas: 2
    # - type: bind
    #   source: ./nginx.conf
    #   target: /etc/nginx/nginx.conf
       #target: /etc/nginx/nginx.conf
    ports:
      - "20000:80"
