version: '3.3'
services:
  fluentd:
    image: fluentd
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - 24224:24224
      - 5140:5140/udp
      - 2020:2020
    logging:
        driver: "json-file"
        options:
            max-size: 100m
            max-file: "5"
#    deploy:
#      mode: 'global'
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - elastic

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    container_name: es01
    ports:
      - "9200:9200"
    networks:
      - elastic
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=false
      - cluster.initial_master_nodes=es01
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.1
    container_name: kib01
    links:
      - "elasticsearch"
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elastic
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.nginx.loadbalancer.server.port=5601"
      - "traefik.http.routers.nginx.rule=HostRegexp(`kibana.{ip:.*}.nip.io`)"
      - "traefik.http.routers.nginx.entrypoints=web"
      - "traefik.http.routers.nginx-https.rule=HostRegexp(`kibana.{ip:.*}.nip>"
      - "traefik.http.routers.nginx-https.entrypoints=web-secured"
      - "traefik.http.middlewares.test-auth.basicauth.users=rebrainme:DockerRocks!"

networks:
  elastic:
    driver: overlay
